[project]
name = "articles"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "google-genai>=2.16.0",
    "python-dotenv>=1.2.2",
    "pyyaml>=6.0.3",
    "upstash-redis>=1.7.0",
    "upstash-vector>=0.6.0",
    "uvicorn>=0.52.0",
]
